INDEX = {
    'bm25': {
        'dl19': 'msmarco-v1-passage',
        'dl20': 'msmarco-v1-passage',
        'covid': 'beir-v1.0.0-trec-covid.flat',
        'arguana': 'beir-v1.0.0-arguana.flat',
        'touche': 'beir-v1.0.0-webis-touche2020.flat',
        'news': 'beir-v1.0.0-trec-news.flat',
        'scifact': 'beir-v1.0.0-scifact.flat',
        'fiqa': 'beir-v1.0.0-fiqa.flat',
        'scidocs': 'beir-v1.0.0-scidocs.flat',
        'nfc': 'beir-v1.0.0-nfcorpus.flat',
        'quora': 'beir-v1.0.0-quora.flat',
        'dbpedia': 'beir-v1.0.0-dbpedia-entity.flat',
        'fever': 'beir-v1.0.0-fever.flat',
        'robust04': 'beir-v1.0.0-robust04.flat',
        'signal': 'beir-v1.0.0-signal1m.flat',
        'nq': 'beir-v1.0.0-nq.flat',
        'cfever': 'beir-v1.0.0-climate-fever.flat',
        'hotpotqa': 'beir-v1.0.0-hotpotqa.flat',
    },
    'splade++ed': {
        'dl19': 'msmarco-v1-passage-splade-pp-ed-text',
        'dl20': 'msmarco-v1-passage-splade-pp-ed-text',
        'covid': 'beir-v1.0.0-trec-covid.splade-pp-ed',
        'arguana': 'beir-v1.0.0-arguana.splade-pp-ed',
        'touche': 'beir-v1.0.0-webis-touche2020.splade-pp-ed',
        'news': 'beir-v1.0.0-trec-news.splade-pp-ed',
        'scifact': 'beir-v1.0.0-scifact.splade-pp-ed',
        'fiqa': 'beir-v1.0.0-fiqa.splade-pp-ed',
        'scidocs': 'beir-v1.0.0-scidocs.splade-pp-ed',
        'nfc': 'beir-v1.0.0-nfcorpus.splade-pp-ed',
        'quora': 'beir-v1.0.0-quora.splade-pp-ed',
        'dbpedia': 'beir-v1.0.0-dbpedia-entity.splade-pp-ed',
        'fever': 'beir-v1.0.0-fever.splade-pp-ed',
        'robust04': 'beir-v1.0.0-robust04.splade-pp-ed',
        'signal': 'beir-v1.0.0-signal1m.splade-pp-ed',
        'nq': 'beir-v1.0.0-nq.splade-pp-ed',
        'cfever': 'beir-v1.0.0-climate-fever.splade-pp-ed',
        'hotpotqa': 'beir-v1.0.0-hotpotqa.splade-pp-ed'
    },
    'dense': {
        'dl19': 'msmarco-v1-passage',
        'dl20': 'msmarco-v1-passage',
        'covid': 'trec-covid',
        'arguana': 'arguana',
        'touche': 'webis-touche2020',
        'news': 'trec-news',
        'scifact': 'scifact',
        'fiqa': 'fiqa',
        'scidocs': 'scidocs',
        'nfc': 'nfcorpus',
        'quora': 'quora',
        'dbpedia': 'dbpedia-entity',
        'fever': 'fever',
        'robust04': 'robust04',
        'signal': 'signal1m',
        'nq': 'nq',
        'cfever': 'climate-fever',
        'hotpotqa': 'hotpotqa'
    }
}

TOPICS = {
    'dl19': 'dl19-passage',
    'dl20': 'dl20-passage',
    'covid': 'beir-v1.0.0-trec-covid-test',
    'arguana': 'beir-v1.0.0-arguana-test',
    'touche': 'beir-v1.0.0-webis-touche2020-test',
    'news': 'beir-v1.0.0-trec-news-test',
    'scifact': 'beir-v1.0.0-scifact-test',
    'fiqa': 'beir-v1.0.0-fiqa-test',
    'scidocs': 'beir-v1.0.0-scidocs-test',
    'nfc': 'beir-v1.0.0-nfcorpus-test',
    'quora': 'beir-v1.0.0-quora-test',
    'dbpedia': 'beir-v1.0.0-dbpedia-entity-test',
    'fever': 'beir-v1.0.0-fever-test',
    'robust04': 'beir-v1.0.0-robust04-test',
    'signal': 'beir-v1.0.0-signal1m-test',
    'nq': 'beir-v1.0.0-nq-test',
    'cfever': 'beir-v1.0.0-climate-fever-test',
    'hotpotqa': 'beir-v1.0.0-hotpotqa-test',
}
